//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        public System.Guid ID { get; set; }
        public System.Guid IDTEACHER { get; set; }
        public System.Guid IDSUBJECT { get; set; }
        public System.Guid IDCLASS { get; set; }
        public System.Guid IDSCHEDULE { get; set; }
        public Nullable<byte> TIMESTART { get; set; }
        public Nullable<byte> TIMEEND { get; set; }
        public Nullable<byte> DAYOFW { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
