//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudMinDBEntities : DbContext
    {
        public StudMinDBEntities()
            : base("name=StudMinDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS> CLASSes { get; set; }
        public virtual DbSet<LIMIT> LIMITs { get; set; }
        public virtual DbSet<ROLESUBJECT> ROLESUBJECTs { get; set; }
        public virtual DbSet<SCORE> SCOREs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STAFFROLE> STAFFROLEs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDYING> STUDYINGs { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
        public virtual DbSet<TEACH> TEACHes { get; set; }
        public virtual DbSet<TEACHER> TEACHERs { get; set; }
        public virtual DbSet<TEACHERROLE> TEACHERROLEs { get; set; }
        public virtual DbSet<TRANSCRIPT> TRANSCRIPTs { get; set; }
        public virtual DbSet<USERROLE> USERROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
        public virtual DbSet<INFOR> INFORs { get; set; }
        public virtual DbSet<LESSON> LESSONs { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
    }
}
