//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> MIN { get; set; }
        public Nullable<int> MAX { get; set; }
    }
}
