//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORE
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDSUBJECT { get; set; }
        public Nullable<System.Guid> IDSTUDENT { get; set; }
        public Nullable<double> SCORE1 { get; set; }
        public string SCHOOLYEAR { get; set; }
        public Nullable<System.Guid> IDROLESCORE { get; set; }
        public Nullable<System.Guid> IDSEMESTER { get; set; }
    
        public virtual ROLESCORE ROLESCORE { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
