//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDUSER { get; set; }
        public Nullable<System.Guid> IDSTAFFROLE { get; set; }
        public Nullable<System.Guid> IDINFOR { get; set; }
    
        public virtual INFOR INFOR { get; set; }
        public virtual STAFFROLE STAFFROLE { get; set; }
        public virtual USER USER { get; set; }
    }
}
