//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.CLASSes = new HashSet<CLASS>();
            this.SUBJECTs = new HashSet<SUBJECT>();
            this.TEACHes = new HashSet<TEACH>();
            this.LESSONs = new HashSet<LESSON>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDUSER { get; set; }
        public Nullable<System.Guid> IDTEACHERROLE { get; set; }
        public Nullable<System.Guid> IDINFOR { get; set; }
        public Nullable<System.Guid> IDSUBJECT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASS> CLASSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT> SUBJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACH> TEACHes { get; set; }
        public virtual TEACHERROLE TEACHERROLE { get; set; }
        public virtual USER USER { get; set; }
        public virtual INFOR INFOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LESSON> LESSONs { get; set; }
    }
}
