//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studMin.Database.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class TRANSCRIPT : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        public System.Guid ID { get; set; }
        public string SCHOOLYEAR { get; set; }
        public Nullable<int> SEMESTER { get; set; }
        public Nullable<System.Guid> IDSTUDENT { get; set; }
        public string RANK { get; set; }

        private Nullable<System.Guid> _idConduct { get; set; }
        public Nullable<System.Guid> IDCONDUCT { get => _idConduct; set { _idConduct = value; OnPropertyChanged(); } }
    
        public virtual CONDUCT CONDUCT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
